# Generated by Django 5.0.14 on 2026-08-21 16:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_business_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vat_return", "VAT return"),
                            ("paye_uif_sdl", "PAYE / UIF / SDL"),
                            ("provisional_tax", "Provisional tax"),
                            ("cipc_annual_return", "CIPC annual return"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
    ]
