# Generated by Django 5.0.14 on 2026-08-21 05:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=accounts.models.logo_upload_path,
            ),
        ),
    ]
