# Generated by Django 5.0.14 on 2026-08-21 05:35

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="expense",
            name="is_vat_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("materials_stock", "Materials & stock"),
                    ("fuel_travel", "Fuel & travel"),
                    ("tools_equipment", "Tools & equipment"),
                    ("rent", "Rent"),
                    ("utilities", "Utilities"),
                    ("insurance", "Insurance"),
                    ("bank_charges", "Bank charges"),
                    ("professional_fees", "Professional fees"),
                    ("marketing", "Marketing & advertising"),
                    ("telephone_internet", "Telephone & internet"),
                    ("vehicle", "Vehicle expenses"),
                    ("repairs_maintenance", "Repairs & maintenance"),
                    ("wages_subcontractors", "Wages & subcontractors"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=finance.models.expense_receipt_upload_path,
            ),
        ),
    ]
