# Generated by Django 5.0.14 on 2026-08-21 05:39

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_expense_options_expense_is_vat_applicable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=finance.models.expense_receipt_upload_path,
            ),
        ),
    ]
