# Generated by Django 5.0.14 on 2026-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_expense_receipt_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
